In [9]:
import seaborn as sns
import pandas as pd

df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [16]:
print(df.describe(include='object'))
print(df.describe())

         sex embarked  who  embark_town alive
count    891      889  891          889   891
unique     2        3    3            3     2
top     male        S  man  Southampton    no
freq     577      644  537          644   549
         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [18]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [33]:
df['age'].value_counts()

# Do every formatting like remove evey inconsistent data format
df['age'] = df['age'].round(0)

# Once the things has done at eventually go for .fillna()
df['age'] = df['age'].fillna(df['age'].median())

In [44]:
df['sex'].value_counts()
df['sex'] = df['sex'].replace({'male':'Male','female':'Female'})
df['alive'].value_counts()
df['alive'].replace({'no':'No','yes':'Yes'},inplace = True)

C:\Users\SAHU\AppData\Local\Temp\ipykernel_8816\899344446.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['alive'].replace({'no':'No','yes':'Yes'},inplace = True)

In [6]:
rd = pd.read_csv(r'C:\Users\SAHU\OneDrive\Desktop\retail_sales_50k.csv')
rd.info()
rd.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 29 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          50000 non-null  object
 1   Customer_ID       50000 non-null  object
 2   Product_ID        50000 non-null  object
 3   Product_Name      50000 non-null  object
 4   Category          50000 non-null  object
 5   Order_Date        50000 non-null  object
 6   Ship_Date         50000 non-null  object
 7   Delivery_Date     50000 non-null  object
 8   Ship_Days         50000 non-null  int64
 9   City              50000 non-null  object
 10  State             50000 non-null  object
 11  Customer_Gender   50000 non-null  object
 12  Customer_Age      50000 non-null  int64
 13  Customer_Segment  50000 non-null  object
 14  Quantity          50000 non-null  int64
 15  Unit_Price        50000 non-null  float64
 16  Discount_%        50000 non-null  int64
 17  Discount_Amount   50000 non-null  float64
 18  Sales             50000 non-null  float64
 19  COGS              50000 non-null  float64
 20  Profit            50000 non-null  float64
 21  Profit_Margin_%   50000 non-null  float64
 22  Shipping_Cost     50000 non-null  float64
 23  Payment_Method    50000 non-null  object
 24  Sales_Channel     50000 non-null  object
 25  Shipping_Mode     50000 non-null  object
 26  Is_Returned       50000 non-null  object
 27  Return_Reason     4074 non-null   object
 28  Customer_Rating   45019 non-null  float64
dtypes: float64(8), int64(4), object(17)
memory usage: 11.1+ MB

Order_ID                0
Customer_ID             0
Product_ID              0
Product_Name            0
Category                0
Order_Date              0
Ship_Date               0
Delivery_Date           0
Ship_Days               0
City                    0
State                   0
Customer_Gender         0
Customer_Age            0
Customer_Segment        0
Quantity                0
Unit_Price              0
Discount_%              0
Discount_Amount         0
Sales                   0
COGS                    0
Profit                  0
Profit_Margin_%         0
Shipping_Cost           0
Payment_Method          0
Sales_Channel           0
Shipping_Mode           0
Is_Returned             0
Return_Reason       45926
Customer_Rating      4981
dtype: int64

In [42]:
rd['Product_Name'].value_counts()
rd['Product_Name'].unique()

rd['Category'].value_counts()

rd['Order_Date'].unique()
rd['Order_Date'] = pd.to_datetime(rd['Order_Date'])

rd['Ship_Date']
rd['Ship_Date'] = pd.to_datetime(rd['Ship_Date'])

rd['Delivery_Date']
rd['Delivery_Date'] = pd.to_datetime(rd['Delivery_Date'])

rd['Ship_Days']

rd['City'].value_counts()
rd['State'].value_counts()

rd['Customer_Gender'].value_counts()
rd['Customer_Segment'].value_counts()

rd['Payment_Method'].value_counts()
rd['Sales_Channel'].value_counts()

rd.describe()
rd['Customer_Rating'].fillna(rd['Customer_Rating'].mean(),inplace = True)
rd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          50000 non-null  object
 1   Customer_ID       50000 non-null  object
 2   Product_ID        50000 non-null  object
 3   Product_Name      50000 non-null  object
 4   Category          50000 non-null  object
 5   Order_Date        50000 non-null  datetime64[ns]
 6   Ship_Date         50000 non-null  datetime64[ns]
 7   Delivery_Date     50000 non-null  datetime64[ns]
 8   Ship_Days         50000 non-null  int64
 9   City              50000 non-null  object
 10  State             50000 non-null  object
 11  Customer_Gender   50000 non-null  object
 12  Customer_Age      50000 non-null  int64
 13  Customer_Segment  50000 non-null  object
 14  Quantity          50000 non-null  int64
 15  Unit_Price        50000 non-null  float64
 16  Discount_%        50000 non-null  int64
 17  Discount_Amount   50000 non-null  float64
 18  Sales             50000 non-null  float64
 19  COGS              50000 non-null  float64
 20  Profit            50000 non-null  float64
 21  Profit_Margin_%   50000 non-null  float64
 22  Shipping_Cost     50000 non-null  float64
 23  Payment_Method    50000 non-null  object
 24  Sales_Channel     50000 non-null  object
 25  Shipping_Mode     50000 non-null  object
 26  Is_Returned       50000 non-null  object
 27  Customer_Rating   50000 non-null  float64
dtypes: datetime64[ns](3), float64(8), int64(4), object(13)
memory usage: 10.7+ MB

C:\Users\SAHU\AppData\Local\Temp\ipykernel_8572\703997816.py:27: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  rd['Customer_Rating'].fillna(rd['Customer_Rating'].mean(),inplace = True)

# Retreving data from SQL database for - DATA CLEANING

In [7]:
!pip install  mysql-connector-python
!pip install sqlalchemy

from urllib.parse import quote_plus
passcode = quote_plus('sahu20031004@gmail.com')

from sqlalchemy import create_engine
engine = create_engine(f"mysql+mysqlconnector://root:{passcode}@localhost/readme_unlceaned")

In [5]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [14]:
from urllib.parse import quote_plus
passcode = quote_plus('sahu20031004@gmail.com')

from sqlalchemy import create_engine
engine = create_engine(f"mysql+pymysql://root:{passcode}@localhost/readme_uncleaned")

print(engine.url)

query = 'select * from raw_employee_data'
employee_data = pd.read_sql(query,engine)
employee_data

mysql+pymysql://root:***@localhost/readme_uncleaned

,Employee_ID,Full_Name,Age,Gender,Department,City,Salary,Joining_Date,Performance_Rating,Email
0,1530,Navya Verma,29.0,f,legal,Delhi,120913.0,18.02.2023,4.0,navya.verma@outlook.com
1,1712,Reyansh Gupta,23.0,Female,marketing,gurugram,142630.0,2015/07/03,5.0,reyansh.gupta@gmail.com
2,1007,Sarah Bansal,56.0,MALE,I.T.,kolkata,146754.0,06-Jul-2019,3.0,sarah.bansal@gmail.com
3,1247,Karan Tiwari,28.0,Male,Cust. Support,Calcutta,40833.0,30/01/2018,5.0,karan.tiwari@ outlook.com
4,1058,Sneha Aggarwal,45.0,FEMALE,SALES,DELHI,62243.0,2018/05/16,3.0,sneha.aggarwal@company.co.in
...,...,...,...,...,...,...,...,...,...,...
709,1844,Vivaan Smith,57.0,MALE,Finance,HYDERABAD,91044.0,2026/05/18,3.0,vivaan.smith@yahoo.com
710,1760,William Mishra,45.0,Female,customer support,PUNE,97168.0,07-Jan-2022,4.0,william.mishra@company.co.in
711,1598,Joseph Kapoor,26.0,f,Sales,Madras,84606.0,19-Mar-2021,1.0,joseph.kapoor@company.co.in
712,1748,William Verma,56.0,FEMALE,Human Resources,HYDERABAD,64798.0,10.02.2020,3.0,william.verma@gmail.com
713,1681,Priya Davis,34.0,M,Finance,Pune,94866.0,11-03-2025,5.0,priya.davis@yahoo.com

In [16]:
employee_data.info()
employee_data.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714 entries, 0 to 713
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         714 non-null    int64
 1   Full_Name           714 non-null    object
 2   Age                 705 non-null    float64
 3   Gender              703 non-null    object
 4   Department          712 non-null    object
 5   City                709 non-null    object
 6   Salary              703 non-null    float64
 7   Joining_Date        709 non-null    object
 8   Performance_Rating  704 non-null    float64
 9   Email               707 non-null    object
dtypes: float64(3), int64(1), object(6)
memory usage: 55.9+ KB

Employee_ID            0
Full_Name              0
Age                    9
Gender                11
Department             2
City                   5
Salary                11
Joining_Date           5
Performance_Rating    10
Email                  7
dtype: int64

In [23]:
print(employee_data.describe(include = 'object'))
print(employee_data.describe())

           Full_Name  Gender Department       City Joining_Date Email
count            714     703        712        709          709   707
unique           595      18         38         39          644   618
top     Suresh Reddy  FEMALE      legal  HYDERABAD   2026-13-45   N/A
freq               4      82         37         36           10     6
       Employee_ID         Age        Salary  Performance_Rating
count   714.000000  705.000000  7.030000e+02          704.000000
mean   1423.260504   43.039716  1.113077e+05            3.039773
std     245.639834   52.679467  3.718276e+05            1.572744
min    1002.000000   -5.000000 -1.000000e+03           -1.000000
25%    1206.250000   30.000000  5.237300e+04            2.000000
50%    1426.500000   41.000000  8.214000e+04            3.000000
75%    1635.750000   50.000000  1.123155e+05            4.000000
max    1850.000000  999.000000  5.000000e+06           10.000000

In [27]:
employee_data['Age'] = employee_data['Age'].fillna(employee_data['Age'].median())

In [41]:
employee_data['Age'] = employee_data['Age'].mask(employee_data['Age'] > 99, employee_data['Age'].median())
employee_data['Age'] = employee_data['Age'].mask(employee_data['Age'] < 18, employee_data['Age'].median())

In [60]:
employee_data['Gender'] = employee_data['Gender'].fillna(employee_data['Gender'].mode()[0])

array(['Female', 'Male'], dtype=object)

In [59]:
employee_data['Gender'] = employee_data['Gender'].str.strip()
employee_data['Gender'] = employee_data['Gender'].str.lower()
employee_data['Gender'] = employee_data['Gender'].str.title()
employee_data['Gender'] = employee_data['Gender'].replace({'' : 'Male'})

In [61]:
employee_data['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [72]:
employee_data[employee_data['Department'].isna()]
employee_data['Department'].unique()
employee_data['Department'] = employee_data['Department'].str.strip()
employee_data['Department'] = employee_data['Department'].str.upper()
employee_data['Department'] = employee_data['Department'].str.lower()
employee_data['Department'] = employee_data['Department'].str.title()
employee_data['Department'] = employee_data['Department'].replace({'Cs':'Customer Support','It':'Information Technology','I.T.':'Information Technology','Cust. Support':'Customer Support','Mktg':'Marketing','Sale':'Sales','Hr':'Human Resources','Fin':'Finance','H.R.':'Human Resources'})

In [74]:
employee_data['Department'].value_counts()
employee_data['Department'] = employee_data['Department'].fillna(employee_data['Department'].mode()[0])

In [79]:
employee_data['Department'].value_counts()
employee_data['Department'] = employee_data['Department'].replace({'Missing':'Customer Support','Na':'Marketing','-':'Information Technology',' ':'Customer Support','':'Customer Support'})

In [85]:
employee_data['Department'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 714 entries, 0 to 713
Series name: Department
Non-Null Count  Dtype
--------------  -----
714 non-null    object
dtypes: object(1)
memory usage: 5.7+ KB

In [88]:
employee_data['City'].value_counts()
employee_data['City'] = employee_data['City'].str.strip()
employee_data['City'] = employee_data['City'].str.upper()
employee_data['City'] = employee_data['City'].str.lower()
employee_data['City'] = employee_data['City'].str.title()

In [95]:
employee_data['City'].value_counts()
employee_data['City'] = employee_data['City'].replace({'Bengaluru':'Bangalore','Calcutta':'Kolkata','Bombay':'Mumbai','':'Bangalore','?':'Pune','Na':'Hyderabad','Missing':'Kolkata','Mumai':'Mumbai','N/A':'Delhi'})

In [102]:
employee_data['City'] = employee_data['City'].fillna(employee_data['City'].mode()[0])
employee_data['City']

0          Delhi
1       Gurugram
2        Kolkata
3        Kolkata
4          Delhi
         ...
709    Hyderabad
710         Pune
711       Madras
712    Hyderabad
713         Pune
Name: City, Length: 714, dtype: object

In [106]:
employee_data['Salary'] = employee_data['Salary'].fillna(employee_data['Salary'].mean())
employee_data['Salary'].isna().sum()

np.int64(0)

In [112]:
employee_data['Joining_Date'].value_counts()
employee_data['Joining_Date'] = employee_data['Joining_Date'].str.strip()

In [116]:
employee_data['Joining_Date'] = employee_data['Joining_Date'].str.replace('.', '-')
employee_data['Joining_Date'] = employee_data['Joining_Date'].str.replace('/', '-')

In [122]:
employee_data['Joining_Date'].value_counts()
employee_data['Joining_Date'] = pd.to_datetime(
    employee_data['Joining_Date'],
    format='mixed',
    dayfirst=True,
    errors='coerce')

In [140]:
employee_data['Joining_Date'] = employee_data['Joining_Date'].fillna(employee_data['Joining_Date'].bfill())

In [143]:
employee_data['Performance_Rating'] = employee_data['Performance_Rating'].fillna(employee_data['Performance_Rating'].mean())

In [145]:
employee_data['Email'] = employee_data['Email'].fillna('Not Available')

In [151]:
employee_data['Email'] = employee_data['Email'].replace({'NA':'Not Available','-':'Not Available'})

In [152]:
employee_data['Email'].value_counts()

Email
Not Available                   26
suresh.reddy@company.co.in       4
ananya.mishra@outlook.com        4
linda.rao@gmail.com              3
elizabeth.bansal@outlook.com     3
                                ..
vikram.rao@company.co.in         1
sarah.wilson@outlook.com         1
rahul.saxena@gmail.com           1
vihaan.wilson@company.co.in      1
priya.davis@yahoo.com            1
Name: count, Length: 615, dtype: int64

# After Data Cleaning, Transfer data in SQL

In [155]:
employee_data.to_sql('employee_data_cleaned', engine, if_exists='replace', index=False)

714