In [1]:
print("Sharad")

Sharad

In [2]:
name = input("Enter your name buddy :")
age = int(input('Put your age :'))
print(name,", Welcome to python class")
print(type(name),type(age))

Enter your name buddy : SKS
Put your age : 22

SKS , Welcome to python class
<class 'str'> <class 'int'>

In [19]:
str = 'Data Anaytics'
print(str[-9:-1])
print(str[-9:])
print(str[:]) # it will print all the characters

# Stepping [starting:ending:steps]
print(str[::2])
print(str[::-1])

 Anaytic
 Anaytics
Data Anaytics
Dt nyis
scityanA ataD

In [5]:
learn = "Hey friends, how the people of West Bengal is feeling after the election won by BJP after 15 yrs."
First_10_Char = learn[:11]
Last_10_Char = learn[-10:]
print(First_10_Char,Last_10_Char)
print(First_10_Char)

Hey friends er 15 yrs.
Hey friends

In [13]:
x = 'Confusing'
y = 'Strings'

new_x = x[:3]+y[3:]
new_y = y[:3]+x[3:]

print(new_x,new_y)

Conings Strfusing

In [3]:
print(age)

22

In [ ]:
                                                        ''' WHILE & FOR LOOP '''

In [6]:
i = '*'
for y in range(1,8):
    z = i*y
    print(z)

*
**
***
****
*****
******
*******

In [10]:
a = "*"
x = int(input("Enter any number : "))
while x > 0:                          # specifying condition is completely necessary in while other wise it will be infinite
    z = a*x
    print(z)
    x-=1

Enter any number : 8

********
*******
******
*****
****
***
**
*

In [ ]:
num = int(input('Num : '))
while num > 0:                    # Fibonacci series - Doubt?

In [12]:

for r in range(1,7):
    print(r + (r-1))

1
3
5
7
9
11

In [4]:
n = int(input('Enter Value : '))
for m in range(n):
    if m%2==0 and m%18==0:
        print(m,"is a even number")
    '''
    else:
        print(m,"is a odd number") '''

Enter Value :  101

0 is a even number
18 is a even number
36 is a even number
54 is a even number
72 is a even number
90 is a even number

In [5]:
n = int(input("Table of : "))
for r in range(1,11):
    t=n*r
    print(t)

Table of :  17

17
34
51
68
85
102
119
136
153
170

In [9]:
for q in range(1,(int(input("Put the Value : "))+1)):
    s = q**2
    print(s)

Put the Value :  10

1
4
9
16
25
36
49
64
81
100

In [18]:
LF = int(input("Lower Fance : "))
UF = int(input("Upper Fance : "))
i = 0
for a in range(LF,(UF+1)):
    i+=a
print("Sum of N natural numbers is",i)

Lower Fance :  1
Upper Fance :  15

Sum of N natural numbers is 120

In [17]:
s = 0
i = int(input("Natural Number : "))
while i>0:
    s+=i
    i-=1
print(s)

Natural Number :  15

120

In [20]:
i = int(input("Enter Any Value : "))
while i>0:
    print(i)
    i-=1

Enter Any Value :  10

10
9
8
7
6
5
4
3
2
1

In [25]:
# Sum all the number of this digit - DOUBT?

num = 123321
x=0
for n in num:
    x+=n
print(x)

123321

In [ ]:
i = 
while i = 0:

In [27]:
char = 'Mr. Pille is looking to investing into our ticket fund, againts a minimal consedration of himself.'

print(char.split(','))
print(char.swapcase())
print(char.upper())
print(char.startswith('m'))
print(char.endswith('.'))
print(char.find('t'))
print(char.index(','))
print(char.strip())

['Mr. Pille is looking to investing into our ticket fund', ' againts a minimal consedration of himself.']
mR. pILLE IS LOOKING TO INVESTING INTO OUR TICKET FUND, AGAINTS A MINIMAL CONSEDRATION OF HIMSELF.
MR. PILLE IS LOOKING TO INVESTING INTO OUR TICKET FUND, AGAINTS A MINIMAL CONSEDRATION OF HIMSELF.
False
True
21
54
Mr. Pille is looking to investing into our ticket fund, againts a minimal consedration of himself.

In [10]:
char1=int(char.index(',')) # it found the place where "," was and then converted it into INT* 
print(char[char1+1:])      # it is for print any digit or alphabets after that index of ,

 againts a minimal consedration of himself.

In [2]:
d = 'DataScience'
print(d[int(d.find('S')):]+d[:4])

ScienceData

In [6]:
m = 'mississippi'
m.index[].replace('s','S')

'miSSiSSippi'

In [3]:
# Which one is greater 

x = 1
y = 8
z = 41

if x > y and x > z:
    print(x)
elif y > x and y > z:
    print(y)
elif z > x and z > y:
    print(z)

41

In [6]:
print(max(x,y,z))
print(min(x,y,z))

41
1

In [7]:
int = int(input("Enter Any Value : "))
for m in range(1,11):
    y = int*m
    print(y)

3
6
9
12
15
18
21
24
27
30

In [8]:
num = [2,3,4,5,6,7,8,9,10,11,12,13,14,15]
submission = 0
for n in num:
    if n%2==0:
        submission+=n
print(submission)

56

In [13]:
num = [2,3,5,10]
oplist = []
for n in num:
    new = n*2
    oplist.append(new)

print(oplist)

[4, 6, 10, 20]

In [15]:
''' replace the elements in old list '''

In [28]:
l = ['a','v','g','h','r','h','q']
del l[1]

In [26]:
l

['v', 'g', 'h', 'r', 'h', 'q']

In [56]:
Ls = ['a','v','g','h','r','h','q']

Ls.pop(0)
Ls

['v', 'g', 'h', 'r', 'h', 'q']

In [ ]:
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Questions from this website - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

In [ ]:
- - - - - - - - - - - - - - - - - - - - - ''' https://pynative.com/python-list-exercise-with-solutions/ ''' - - - - - - - - - - - - - - - - - - - - -

In [58]:
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

In [6]:
numbers = [10, 20, 30, 40, 50]
print(numbers[2])
print(len(numbers))
print(len(numbers)==0)

30
5
False

In [3]:
List = [100, 50, 400, 500]
List[1] = 200
print(List)
print(List.append(600))
print(List)
print(List.insert(2,300))
print(List)
print(List.remove(600))
print(List)
print(List.pop(0))
print(List)

print(sum(List)/len(List))

[100, 200, 400, 500]
None
[100, 200, 400, 500, 600]
None
[100, 200, 300, 400, 500, 600]
None
[100, 200, 300, 400, 500]
100
[200, 300, 400, 500]
350.0

In [4]:
Data = [45, 12, 89, 2, 67]
print(max(Data))
print(min(Data))

89
2

In [5]:
Factors = [2, 3, 5, 7]
m = 1
for f in Factors:
    m*=f
print(m)

210

In [11]:
num =  [10, 21, 4, 45, 66, 93, 11]
odd = 0
even = 0
for n in num :
    if n%2==0:
        even+=1
    else:
        odd+=1

print(odd)
print(even)

4
3

In [8]:
# Doubt -------------------------------------------

num =  [10, 21, 4, 45, 66, 93, 11]
#print(num.sort(reverse = True))
#print(num.sort())
num.reverse()
print(num)

List= [10, 20, 10, 30, 40, 40, 20, 50]   # Remove all the duplicates
num =  [10, 21, 4, 45, 66, 93, 11]       # find the second largest value

dict1 = {"a": 1, "b": 2}
dict2 = {"b": 3, "c": 4}                 # how to merge both dictionary

[11, 93, 66, 45, 4, 21, 10]

In [23]:
Original= ["Apple", "Banana", "Cherry"]
copies = Original.copy()
copies
ist= [23, 65, 19, 90]
copy = ist.copy()
if ist[0] == copy[0]:
    ist[0] = copy[2]
if ist[2] == copy[2] :
    ist[2] = copy[0]

ist

[19, 65, 23, 90]

In [51]:
nl = [[1, 2], [3, 4, 5], [6, 7]]
#print(nl[1][2])

nl = ["Laptop", "Mouse", "Monitor", "Keyboard"]
print("Tablet" in nl)

for l in nl:
    if l == "Tablet":
        print('in the list')
    else:
        print('not in list')

n = ["PHP", "Exercises", "Backend", "Python"]
#print(max(n,key=len))

m = [1, 2, 3, 4, 5]
o = []
for s in m:
    k = s**2
    o.append(k)
#print(o)

p = [10, 20, 30, 10, 40, 10, 50]
print(p.count(10))

q = [5, 20, 15, 20, 25, 50, 20]
for z in q:
    if z == 20:
        q.remove(z)

#print(q)

s = ["Mike", "", "Emma", "Kelly", "", "Brad"]
for xx in s:
    if xx == '':
        s.remove(xx)

#print(s)

st1 = ["Py", "is", "awes"]
st2 = ["thon", " ", "ome"]
new = []
for  r in range(3):
    w = st1[r]+st2[r]
    new.append(w)

#print(new)

d1 = [10, 20, 30]
d2 = [100, 200, 300]

for r in range(3):
    print(d1[r],d2[r])

f = [10,20,30,40,50]
for r in range(len(f)):
    if f[r] == 30:
        f.pop
        f[r] = 35

#print(f)

False
not in list
not in list
not in list
not in list
3
10 100
20 200
30 300

In [51]:
student = {"name": "Alice", "age": 20, "grade": "B"}
student["City"] = "New York"
student.values()
student.items()
student.get("name")

car = {"brand": "Toyota", "model": "Camry", "year": 2022, "color": "blue"}
car.popitem()
car.items()
"brand" in car
"color" in car

keys = ["name", "age", "city"]
values = ["Bob", 25, "London"]
dct = dict(zip(keys,values))
dct
dct.clear()
dct

dict1 = {"a": 1, "b": 2}
dict2 = {"b": 3, "c": 4}

person = {"name": "Carol", "address": {"city": "Paris", "zip": "75001"}}
person['address'].get("city")

'Paris'

In [14]:
c= "abc123xyz"
p=""
q=""
for i in range(1,10):
    for a in c:
        if i == a:
            p+=i

print(q)

In [3]:
word = "cofee-tofee"
freq = {}
for c in word:
    if c in freq:
        freq[c]+=1
    else:
        freq[c] = 1
print(freq)

4

In [10]:
car = {"brand": 75, "model": 1, "year": 2022, "color": 85}
min(car.keys(),key=len)
max(car.values())

2022

In [ ]:
# ----------------------------------- PANDAS --------------------------------

In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\SAHU\OneDrive\Desktop\Data Analytic\SQL\Assignment\Practise\HR Data\Employees.csv")
df

df.shape
df.describe()
df.size
len(df) # printing the numbers of rows
df.info()
df.count()

df['salary'].dtype
df['job_role'].dtype
df['new'] = df['emp_id'] + df['salary']
df   # new column has added successfully

df[df['salary']>100000]
df[df['salary']>100000].shape
df['salary'].isna

''' df[0] ''' # indexing will not work only slicing work
df['name'][45]
df[0:10]  # 0 rows se 10th rows tak - for view

df.loc[5,'hire_date']
df[df['hire_date'].isna()]
df.loc[df['hire_date'].isna()]

# for manupulation
df['hire_date'] = df['hire_date'].replace('2024-09-09','2024-09-19')
df.loc[5,'salary'] = 100000
df['salary'] = np.where(df['salary']>100000,100000,df['salary'])                  # """ Doubt & if we want to use else if as well? """
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      3000 non-null   int64
 1   name        3000 non-null   object
 2   department  3000 non-null   object
 3   job_role    3000 non-null   object
 4   location    3000 non-null   object
 5   hire_date   3000 non-null   object
 6   salary      3000 non-null   int64
 7   status      3000 non-null   object
dtypes: int64(2), object(6)
memory usage: 187.6+ KB

,emp_id,name,department,job_role,location,hire_date,salary,status,new
0,1,Emp_1,Sales,Analyst,Kolkata,2020-04-06,100000,Resigned,118768
1,2,Emp_2,Marketing,Associate,Mumbai,2019-06-23,91908,On Leave,91910
2,3,Emp_3,Operations,Associate,Mumbai,2020-02-23,100000,Resigned,144202
3,4,Emp_4,Operations,Lead,Chennai,2022-04-08,87728,Active,87732
4,5,Emp_5,IT,Associate,Delhi,2019-11-01,60722,On Leave,60727
...,...,...,...,...,...,...,...,...,...
2995,2996,Emp_2996,IT,Lead,Kolkata,2019-06-21,100000,Active,138380
2996,2997,Emp_2997,Operations,Analyst,Bangalore,2021-10-08,80162,Active,83159
2997,2998,Emp_2998,IT,Manager,Chennai,2024-09-29,100000,Active,128445
2998,2999,Emp_2999,Finance,Manager,Bangalore,2023-11-19,84912,Active,87911
2999,3000,Emp_3000,Operations,Analyst,Chennai,2018-03-19,100000,Active,129845

,emp_id,name,department,job_role,location,hire_date,salary,status,new
0,1,Emp_1,Sales,Analyst,Kolkata,2020-04-06,100000,Resigned,118768
1,2,Emp_2,Marketing,Associate,Mumbai,2019-06-23,91908,On Leave,91910
2,3,Emp_3,Operations,Associate,Mumbai,2020-02-23,100000,Resigned,144202
3,4,Emp_4,Operations,Lead,Chennai,2022-04-08,87728,Active,87732
4,5,Emp_5,IT,Associate,Delhi,2019-11-01,60722,On Leave,60727
...,...,...,...,...,...,...,...,...,...
2995,2996,Emp_2996,IT,Lead,Kolkata,2019-06-21,100000,Active,138380
2996,2997,Emp_2997,Operations,Analyst,Bangalore,2021-10-08,80162,Active,83159
2997,2998,Emp_2998,IT,Manager,Chennai,2024-09-29,100000,Active,128445
2998,2999,Emp_2999,Finance,Manager,Bangalore,2023-11-19,84912,Active,87911
2999,3000,Emp_3000,Operations,Analyst,Chennai,2018-03-19,100000,Active,129845

In [6]:
import pandas as pd
import numpy as np

sd = pd.read_excel(r"C:\Users\SAHU\OneDrive\Desktop\Data Analytic\Python\Practice for data cleaning\Sales_Data.xlsx")
prd = pd.read_excel(r"C:\Users\SAHU\OneDrive\Desktop\Data Analytic\Python\Practice for data cleaning\Product_data.xlsx")
cd = pd.read_excel(r"C:\Users\SAHU\OneDrive\Desktop\Data Analytic\Python\Practice for data cleaning\Customer_data.xlsx")

df.head() # top 5 rows
df.tail() # las 5 rows
df.shape
df.columns # display of columns
df.describe()
sd.info()

sd['Sales']
sd['Sales'].head()
sd['Sales'][0:20]
sd[['City','Profit']]
#sd[['City','Profit']].dtype                         """ Doubt"""
sd[0:20]
sd[50:(100+1)]

sd[sd['Sales']>50000]
sd[sd['City'] == 'Delhi']
sd[(sd['Product_ID']) & (sd['Profit']>10000)]      # Doubt - If I want only these two columns so how would we get '''
sd[sd['Quantity']>3]
prd[prd['Category'] == 'Electronics']
prd['Category'].count()                            # How many distinct categories and thier counts and is there any update function in pd 
sd['Profit_Margin'] = (sd['Profit']/sd['Sales'])*100                            # another way for altering and updation
sd['Tax'] = .18*sd['Sales']
sd['Invoice'] = 1.18*sd['Sales']
sd['Status'] = np.where(sd['Sales']>50000,'High Sales','Low Sales')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     1000 non-null   int64
 1   Date         1000 non-null   object
 2   Customer_ID  1000 non-null   int64
 3   Product_ID   1000 non-null   int64
 4   City         1000 non-null   object
 5   Sales        1000 non-null   int64
 6   Quantity     1000 non-null   int64
 7   Profit       1000 non-null   int64
dtypes: int64(6), object(2)
memory usage: 62.6+ KB

In [16]:
sd = pd.read_excel(r"C:\Users\SAHU\OneDrive\Desktop\Data Analytic\Python\Practice for data cleaning\Sales_Data.xlsx")
sd['City'].dtype

dtype('O')

In [20]:
sd[sd['Profit']>10000][['Product_ID','Profit']]

     Product_ID  Profit
0            25   12329
1            31   13359
2            21   10342
3            10   11850
4            35   10776
..          ...     ...
979          43   14123
984          22   14286
991          24   12172
994          15   11733
996           3   14856

[335 rows x 2 columns]

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

roe = pd.read_csv(r"C:\Users\SAHU\OneDrive\Desktop\Data Analytic\Python\Practice for data cleaning\roedata.csv")

In [144]:
roe.describe()
roe
roe['Number of firms'][roe['Number of firms']<800].value_counts(bins=10).sort_index()

(2.281, 74.8]     61
(74.8, 146.6]     24
(146.6, 218.4]     5
(218.4, 290.2]     2
(290.2, 362.0]     2
(362.0, 433.8]     1
(433.8, 505.6]     0
(505.6, 577.4]     0
(577.4, 649.2]     0
(649.2, 721.0]     1
Name: count, dtype: int64

In [3]:
#df['hire_date'] = pd.to_datetime(df['hire_date'])
#df['hire_date'].dt.year
#df['hire_date'].dt.month
#df['hire_date'].dt.day
df['hire_date'].dtype
df['hire_date'] = pd.to_datetime(df['hire_date'])               # Doubt - I have to conver m-d-y to y-m-d format

In [10]:
df = pd.read_csv(r"C:\Users\SAHU\OneDrive\Desktop\Data Analytic\SQL\Assignment\Practise\HR Data\Employees.csv")
df['hire_date'] = pd.to_datetime(df['hire_date']).dt.strftime("%d-%m-%Y")
df

,emp_id,name,department,job_role,location,hire_date,salary,status
0,1,Emp_1,Sales,Analyst,Kolkata,06-04-2020,118767,Resigned
1,2,Emp_2,Marketing,Associate,Mumbai,23-06-2019,91908,On Leave
2,3,Emp_3,Operations,Associate,Mumbai,23-02-2020,144199,Resigned
3,4,Emp_4,Operations,Lead,Chennai,08-04-2022,87728,Active
4,5,Emp_5,IT,Associate,Delhi,01-11-2019,60722,On Leave
...,...,...,...,...,...,...,...,...
2995,2996,Emp_2996,IT,Lead,Kolkata,21-06-2019,135384,Active
2996,2997,Emp_2997,Operations,Analyst,Bangalore,08-10-2021,80162,Active
2997,2998,Emp_2998,IT,Manager,Chennai,29-09-2024,125447,Active
2998,2999,Emp_2999,Finance,Manager,Bangalore,19-11-2023,84912,Active
2999,3000,Emp_3000,Operations,Analyst,Chennai,19-03-2018,126845,Active

In [47]:
df[['emp_id','salary','new']].sum()
df[['emp_id','salary','new']].mean()

emp_id     1500.500000
salary    75767.667667
new       86897.999000
dtype: float64

In [93]:
df['location'] = df['location'].str.lower()
df['location'] = df['location'].str.title()
df['name'] = df['name'].str.upper()

#df.describe(inculde=object)
df['location'].value_counts()
df['job_role'].unique()
df['job_role'].nunique()

,Order_ID,Date,Customer_ID,Product_ID,City,Sales,Quantity,Profit,Profit_Margin,Tax,Invoice,Status
0,1001,2024-05-06,92,25,Kolkata,58243,1,12329,21.168209,10483.74,68726.74,High Sales
1,1002,2024-11-02,121,31,Chennai,47427,3,13359,28.167500,8536.86,55963.86,Low Sales
2,1003,2024-10-03,255,21,Delhi,23084,1,10342,44.801594,4155.12,27239.12,Low Sales
3,1004,2024-12-11,261,10,Chennai,67526,2,11850,17.548796,12154.68,79680.68,High Sales
4,1005,2024-04-18,3,35,Pune,12254,5,10776,87.938632,2205.72,14459.72,Low Sales
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1996,2024-04-03,84,26,Pune,56073,4,9944,17.734025,10093.14,66166.14,High Sales
996,1997,2024-07-11,159,3,Mumbai,22948,5,14856,64.737668,4130.64,27078.64,Low Sales
997,1998,2024-10-19,13,31,Delhi,47739,1,5918,12.396573,8593.02,56332.02,Low Sales
998,1999,2024-03-08,263,5,Delhi,2477,3,5007,202.139685,445.86,2922.86,Low Sales
999,2000,2024-07-05,256,29,Bangalore,17811,5,8101,45.483128,3205.98,21016.98,Low Sales

In [130]:
sd.groupby('City')['Customer_ID'].mean()                      # Doubt - How to use round function here 
sd.groupby(['City','Status']).agg({'Profit':['sum','mean']})
sd.sort_values('Profit',ascending = False)                           # Normal values sorting
sd.sort_values('Profit',ascending = False)[['Profit','Product_ID']]  # Products with highest profit 

sd.duplicated()
m1 = pd.merge(sd,prd,on = 'Product_ID',how = 'inner')
o1 = pd.merge(sd,prd,on = 'Product_ID',how = 'outer')
o1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   int64
 1   Date           1000 non-null   object
 2   Customer_ID    1000 non-null   int64
 3   Product_ID     1000 non-null   int64
 4   City           1000 non-null   object
 5   Sales          1000 non-null   int64
 6   Quantity       1000 non-null   int64
 7   Profit         1000 non-null   int64
 8   Profit_Margin  1000 non-null   float64
 9   Tax            1000 non-null   float64
 10  Invoice        1000 non-null   float64
 11  Status         1000 non-null   object
 12  Product_Name   1000 non-null   object
 13  Category       1000 non-null   object
 14  Price          1000 non-null   int64
dtypes: float64(3), int64(7), object(5)
memory usage: 117.3+ KB

In [125]:
m1['Product_Name'].value_counts()
m1.sort_values('Price',ascending = False)
m1.groupby(['Category','Product_Name']).agg({['Price','Profit']:['sum','mean']})   #doubt

SyntaxError: invalid syntax (1867736594.py, line 3)

In [136]:
m1['Profit_Margin'].count()

np.int64(1000)

In [19]:
l = [10,20,30,40,50,60,70,80,90]
list(map(lambda x : x**2,l))

list(filter(lambda x : x%2==0,l))

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [4]:
import pandas as pd
from datetime import datetime
table = pd.read_excel(r"C:\Users\SAHU\OneDrive\Desktop\Raw_Sales_Data_Cleaning_Practice.xlsx")
table.shape
table.info()
table.duplicated()
table[table.duplicated()]
table[table['Order_ID']==1007]
#table['Order_Date'] = pd.to_datetime(table['Order_Date'])
table['Order_Date'] = table['Order_Date'].str.replace('/','-')
table['Order_Date'].size
table['Order_Date']
#table['Order_Date'] = pd.to_datetime(table['Order_Date']).strftime('%YY-%M-%D')
table['Order_Date'] = table['Order_Date'].replace('2025-01-03','03-01-2025')
table['Order_Date'] = pd.to_datetime(table['Order_Date'],format='mixed')
table['Order_Date'].astype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       20 non-null     int64
 1   Order_Date     20 non-null     object
 2   Customer_Name  20 non-null     object
 3   Gender         20 non-null     object
 4   City           20 non-null     object
 5   Product        20 non-null     object
 6   Category       20 non-null     object
 7   Quantity       19 non-null     float64
 8   Unit_Price     20 non-null     int64
 9   Total_Amount   20 non-null     int64
 10  Email          20 non-null     object
 11  Phone          19 non-null     object
dtypes: float64(1), int64(3), object(8)
memory usage: 2.0+ KB

<bound method NDFrame.astype of 0    2025-01-01
1    2025-02-01
2    2025-03-01
3    2025-04-01
4    2025-05-01
5    2025-06-01
6    2025-07-01
7    2025-07-01
8    2025-08-01
9    2025-09-01
10   2025-10-01
11   2025-11-01
12   2025-12-01
13   2025-01-13
14   2025-01-14
15   2025-01-15
16   2025-01-16
17   2025-01-17
18   2025-01-18
19   2025-01-19
Name: Order_Date, dtype: datetime64[ns]>

In [70]:
table.drop_duplicates(inplace = True)
table.isna().sum()
table['Phone'].fillna('No Number')

for i in table['Phone']:
    if len(str(i)) < 10:
        table['Phone'] = table['Phone'].replace('i','No Number')

for col in table.columns:
    if table[col].nunique() < 101:
        print(table[col].value_counts())
        print('-'*50)
    

table['Category'] = table['Category'].replace('Electronic','Electronics')
table['Category'] = table['Category'].replace('electronics','Electronics')
table[table['Category']]

Order_ID
1001    1
1011    1
1018    1
1017    1
1016    1
1015    1
1014    1
1013    1
1012    1
1010    1
1002    1
1009    1
1008    1
1007    1
1006    1
1005    1
1004    1
1003    1
1019    1
Name: count, dtype: int64
--------------------------------------------------
Order_Date
2025-01-01    1
2025-11-01    1
2025-01-18    1
2025-01-17    1
2025-01-16    1
2025-01-15    1
2025-01-14    1
2025-01-13    1
2025-12-01    1
2025-10-01    1
2025-02-01    1
2025-09-01    1
2025-08-01    1
2025-07-01    1
2025-06-01    1
2025-05-01    1
2025-04-01    1
2025-03-01    1
2025-01-19    1
Name: count, dtype: int64
--------------------------------------------------
Customer_Name
Rahul Sharma    3
Pooja Mehta     2
Priya Gupta     1
Amit Verma      1
Neha Singh      1
Ravi Kumar      1
Anjali Jain     1
Karan Kapoor    1
Sneha Roy       1
Arjun Das       1
Meera Shah      1
Rohit Sinha     1
Kavita Rao      1
Mohit Jain      1
Rakesh Gupta    1
Sonal Verma     1
Name: count, dtype: int64
--------------------------------------------------
Gender
Female    9
Male      8
M         1
male      1
Name: count, dtype: int64
--------------------------------------------------
City
Delhi        8
Mumbai       2
Bangalore    2
Chennai      2
Pune         2
MUMBAI       1
Kolkata      1
Bengaluru    1
Name: count, dtype: int64
--------------------------------------------------
Product
Laptop        6
Mobile        3
Keyboard      2
Mouse         2
Printer       2
Monitor       2
Headphones    1
Tablet        1
Name: count, dtype: int64
--------------------------------------------------
Series([], Name: count, dtype: int64)
--------------------------------------------------
Quantity
 1.0    8
 2.0    7
 3.0    1
-1.0    1
 5.0    1
Name: count, dtype: int64
--------------------------------------------------
Unit_Price
55000    6
25000    3
1200     2
800      2
12000    2
15000    2
1500     1
18000    1
Name: count, dtype: int64
--------------------------------------------------
Total_Amount
 55000     3
 50000     3
 110000    2
 2400      2
 12000     2
 30000     2
 25000     1
 4500      1
-800       1
 18000     1
 4000      1
Name: count, dtype: int64
--------------------------------------------------
Email
rahul@gmail.com     3
pooja@gmail.com     2
priyagmail.com      1
amit@gmail.com      1
neha@gmail.com      1
ravi@gmail.com      1
anjali@gmail.com    1
karan@gmail.com     1
sneha@gmail.com     1
arjun@gmail.com     1
meera@gmail         1
rohit@gmail.com     1
kavita@gmail.com    1
mohit@gmail.com     1
rakesh@gmail.com    1
sonal@gmail.com     1
Name: count, dtype: int64
--------------------------------------------------
Phone
9876543210    3
9876543211    1
9876543212    1
9876543214    1
9876543215    1
12345         1
9876543218    1
9876543219    1
9876543220    1
9876543221    1
abc1234567    1
9876543223    1
9876543225    1
9876543226    1
9876543227    1
9876543228    1
Name: count, dtype: int64
--------------------------------------------------

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [5]:
raw = pd.read_csv(r"C:\Users\SAHU\OneDrive\Desktop\matches.csv")
raw.shape
'''
for col in raw.columns:
    if raw[col].nunique() < 20:
        print(raw[col].value_counts())
        print("-"*50)
'''
raw['city'].value_counts()                                  # For finding unique and incosistent data formatting
raw['city'] = raw['city'].str.strip()                       # if inconsistent data ho toh str formatting se kuch had tk thik ho jati h then,
raw['city'] = raw['city'].str.title()                       # u have to replace, old one with the new one.......
raw['city'] = raw['city'].fillna(raw['city'].mode()[0])     # Filling null values - on the basis of numerical and strings (Last step)

raw['player_of_match'].value_counts()
raw['player_of_match'] = raw['player_of_match'].str.strip()
raw['player_of_match'] = raw['player_of_match'].str.title()
raw['player_of_match'] = raw['player_of_match'].bfill()

raw['winner'] = raw['winner'].str.strip()
raw['winner'] = raw['winner'].str.title()
raw['winner'] = raw['winner'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru','Rising Pune Supergiant':'Rising Pune Supergiants'})
raw['winner'].value_counts()
raw['winner'] = raw['winner'].fillna(raw['winner'].mode()[0])

raw['result_margin'].value_counts()
raw['result_margin'] = raw['result_margin'].fillna(raw['result_margin'].median())

raw['target_runs'] = raw['target_runs'].fillna(raw['target_runs'].median())

raw['target_overs'] = raw['target_overs'].fillna(raw['target_overs'].mean())

raw['method'] = raw['method'].fillna('Not Applicable')

raw[raw.duplicated()]                                       # Find and Remove Duplicated instant
raw['date'] = pd.to_datetime(raw['date'],format = 'mixed')

raw['season'] = raw['season'].replace({'2020/21':'2020','2009/10':'2010','2007/08':'2008'})
                                                            # Checking each columns for inconsistence data format and if there, so replace like below;
for col in ['team1','team2','toss_winner']:
    raw[col] = raw[col].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru','Rising Pune Supergiant':'Rising Pune Supergiants'})
raw.info()

raw['team1'].value_counts()                                 # Change data type at last

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1095 non-null   object
 3   date             1095 non-null   datetime64[ns]
 4   match_type       1095 non-null   object
 5   player_of_match  1095 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1095 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1095 non-null   float64
 14  target_runs      1095 non-null   float64
 15  target_overs     1095 non-null   float64
 16  super_over       1095 non-null   object
 17  method           1095 non-null   object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(1), object(15)
memory usage: 171.2+ KB

team1
Royal Challengers Bengaluru    144
Chennai Super Kings            128
Mumbai Indians                 123
Kolkata Knight Riders          121
Rajasthan Royals               101
Kings XI Punjab                 92
Sunrisers Hyderabad             86
Delhi Daredevils                85
Delhi Capitals                  41
Deccan Chargers                 39
Punjab Kings                    31
Pune Warriors                   23
Lucknow Super Giants            23
Gujarat Titans                  21
Gujarat Lions                   16
Rising Pune Supergiants         14
Kochi Tuskers Kerala             7
Name: count, dtype: int64

In [21]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [2]:
i = 85476310
len(str(i))

8